In [756]:
import numpy as np 
import pandas as pd 
import nltk.corpus
import re
nltk.download('stopwords')
nltk.download('wordnet')
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import matplotlib.pyplot as plt 
%inline

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\999sb\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\999sb\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
UsageError: Line magic function `%inline` not found.


In [757]:
from sklearn import  set_config
set_config(display = 'diagram')

In [758]:
df_NewsDjia = pd.read_csv('News_DJIA.csv', delimiter=',')
df_RedditNews = pd.read_csv('News_reddit.csv', delimiter=',')
df_DjiaStock = pd.read_csv('DJIA_t.csv',delimiter=',')

In [759]:
for i in df_NewsDjia.columns :
    df_NewsDjia[i] = df_NewsDjia[i].astype(str)

In [760]:
df_NewsDjia

Date Label                                               Top1  \
0     2008-08-08     0  b"Georgia 'downs two Russian warplanes' as cou...   
1     2008-08-11     1  b'Why wont America and Nato help us? If they w...   
2     2008-08-12     0  b'Remember that adorable 9-year-old who sang a...   
3     2008-08-13     0  b' U.S. refuses Israel weapons to attack Iran:...   
4     2008-08-14     1  b'All the experts admit that we should legalis...   
...          ...   ...                                                ...   
1984  2016-06-27     0  Barclays and RBS shares suspended from trading...   
1985  2016-06-28     1  2,500 Scientists To Australia: If You Want To ...   
1986  2016-06-29     1                   Explosion At Airport In Istanbul   
1987  2016-06-30     1  Jamaica proposes marijuana dispensers for tour...   
1988  2016-07-01     1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
0               b'BREAKING: Musharraf to be impeached.'   
1           b'Bush puts foot down on Georgian conflict'   
2                    b"Russia 'ends Georgia operation'"   
3     b"When the president ordered to attack Tskhinv...   
4     b'War in South Osetia - 89 pictures made by a ...   
...                                                 ...   
1984  Pope says Church should ask forgiveness from g...   
1985  The personal details of 112,000 French police ...   
1986  Yemeni former president: Terrorism is the offs...   
1987  Stephen Hawking says pollution and 'stupidity'...   
1988   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
0     b'Russia Today: Columns of troops roll into So...   
1     b"Jewish Georgian minister: Thanks to Israeli ...   
2     b'"If we had no sexual harassment we would hav...   
3     b' Israel clears troops who killed Reuters cam...   
4     b'Swedish wrestler Ara Abrahamian throws away ...   
...                                                 ...   
1984  Poland 'shocked' by xenophobic abuse of Poles ...   
1985  S&amp;P cuts United Kingdom sovereign credit r...   
1986  UK must accept freedom of movement to access E...   
1987  Boris Johnson says he will not run for Tory pa...   
1988  The president of France says if Brexit won, so...   

                                                   Top4  \
0     b'Russian tanks are moving towards the capital...   
1     b'Georgian army flees in disarray as Russians ...   
2     b"Al-Qa'eda is losing support in Iraq because ...   
3     b'Britain\'s policy of being tough on drugs is...   
4     b'Russia exaggerated the death toll in South O...   
...                                                 ...   
1984  There will be no second referendum, cabinet ag...   
1985                Huge helium deposit found in Africa   
1986  Devastated: scientists too late to captive bre...   
1987  Six gay men in Ivory Coast were abused and for...   
1988  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
0     b"Afghan children raped with 'impunity,' U.N. ...   
1         b"Olympic opening ceremony fireworks 'faked'"   
2     b'Ceasefire in Georgia: Putin Outmaneuvers the...   
3     b'Body of 14 year old found in trunk; Latest (...   
4     b'Missile That Killed 9 Inside Pakistan May Ha...   
...                                                 ...   
1984      Scotland welcome to join EU, Merkel ally says   
1985  CEO of the South African state broadcaster qui...   
1986  British Labor Party leader Jeremy Corbyn loses...   
1987  Switzerland denies citizenship to Muslim immig...   
1988  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
0     b'150 Russian tanks have entered South Ossetia...   
1     b'What were the Mossad with fraudulent New Zea...   
2     b'Why Microsoft and Intel tried to kill the XO...   
3     b'China h

In [761]:
num_columns = df_NewsDjia.columns.shape[0]
col_names = df_NewsDjia.columns.values.tolist()
col_names = col_names[1:]
df_NewsDjia.loc[:, 'merged'] = ""
for each_col_ind in range(num_columns-1):
    df_NewsDjia.loc[:, 'merged'] =  df_NewsDjia.loc[:, 'merged'] + " " + df_NewsDjia[col_names[each_col_ind]] + " "

In [762]:
df_finalised = df_NewsDjia[['merged']]

In [763]:
# date_numric_stopwords = "THOUSAND MILLION BILLION TRILLION HUNDRED ANNUAL ANNUALLY ANNUM YEAR YEARLY QUARTER QUARTERLY QTR MONTH MONTHLY WEEK WEEKLY DAY DAILY JANUARY FEBRUARY MARCH APRIL MAY JUNE JULY AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER JAN FEB MAR APR MAY JUN JUL AUG SEP SEPT OCT NOV DEC MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY SATURDAY SUNDAY TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN ELEVEN TWELVE THIRTEEN FOURTEEN FIFTEEN SIXTEEN SEVENTEEN EIGHTEEN NINETEEN TWENTY THIRTY FORTY FIFTY SIXTY SEVENTY EIGHTY NINETY FIRST SECOND THIRD FOURTH FIFTH SIXTH SEVENTH EIGHTH NINTH TENTH II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX"
# date_numric_stopwords = date_numric_stopwords.lower()
# date_numric_stopwords = date_numric_stopwords.split(" ")

In [764]:

def remove_unecssary_word(sent):
    sent = sent.replace("b'",'')
    sent = sent.replace('b"','')
    sent = sent.lower()
    sent = re.sub(r"(@\[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", sent)
    stop = stopwords.words('english')
    # stop.extend(date_numric_stopwords)
    sent = " ".join([word for word in sent.split() if word not in (stop)])
    sent = " ".join([WordNetLemmatizer().lemmatize(word) for word in sent.split() ])
    return sent

In [765]:
df_finalised['merged'] = df_finalised['merged'].apply(remove_unecssary_word)

C:\Users\999sb\AppData\Local\Temp\ipykernel_25368\4213319948.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_finalised['merged'] = df_finalised['merged'].apply(remove_unecssary_word)


In [766]:
df_finalised.iloc[0][0]

'0 georgia down two russian warplane country move brink war breaking musharraf impeached russia today column troop roll south ossetia footage fighting youtube russian tank moving towards capital south ossetia reportedly completely destroyed georgian artillery fire afghan child raped impunity un official say sick three year old raped nothing 150 russian tank entered south ossetia whilst georgia shoot two russian jet breaking georgia invades south ossetia russia warned would intervene so side enemy combatent trial nothing sham salim haman sentenced 5 12 year kept longer anyway feel like georgian troop retreat osettain capital presumably leaving several hundred people killed video u prep georgia war russia rice give green light israel attack iran say u veto israeli military ops announcingclass action lawsuit behalf american public fbi sorussia georgia war nyts top story opening ceremony olympics fucking disgrace yet proof decline journalism china tell bush stay country affair world war ii

In [767]:
df_finalised = pd.concat([df_finalised,df_NewsDjia['Label']],axis = 1)

In [768]:
Positive_word = ""
with open('Positive_words.txt', 'r') as file:
    Positive_word = file.read().replace('\n', '')
Positive_word = " ".join([WordNetLemmatizer().lemmatize(word) for word in Positive_word.split(',') ])

In [769]:
Negative_word = ""
with open('Negative_words.txt','r') as file:
    Negative_word = file.read().replace('\n','')
Negative_word = " ".join([WordNetLemmatizer().lemmatize(word) for word in Negative_word.split(',') ])

In [770]:
Positive_word = Positive_word.split(',')
Negative_word = Negative_word.split(',')
Negative_word = Negative_word[0].split()
Positive_word = Positive_word[0].split()

In [771]:
set_post = set(Positive_word)
set_neg = set(Negative_word)
def Count(obj):
    count_post = 1
    count_neg = 1
    obj = obj.split()
    for i in obj:
        if i in set_post:
            count_post = count_post + 1
        elif i in set_neg:
            count_neg = count_neg + 1
    return count_post/count_neg


In [772]:
df_finalised['ratio_pos_neg'] = df_finalised['merged'].apply(Count)
X_data = df_finalised['merged']
# ratio_column = df_finalised['ratio_pos_neg']
# ratio_column = np.array(ratio_column).reshape((-1,1))

In [773]:
Y_data = df_finalised['Label']
Y_data = Y_data.astype(int)

In [774]:
Y_data = np.array(Y_data)
Y_data

array([0, 1, 0, ..., 1, 1, 1])

In [775]:
X_data.shape

(1989,)

In [776]:
x_train , x_test , y_train, y_test = X_data[:1590] , X_data[1591:] , Y_data[:1590] , Y_data[1591:]

In [777]:
tf_idf = TfidfVectorizer(min_df=10)
x_train_tf = tf_idf.fit_transform(x_train)
x_test_tf = tf_idf.transform(x_test)
x_train = x_train_tf.toarray()
x_test = x_test_tf.toarray()

In [778]:
mean_not_zero = x_train[x_train != 0].mean() 
x_train[x_train!=0] = x_train[x_train!=0] -  mean_not_zero
x_test[x_test != 0 ] = x_test[x_test != 0] - mean_not_zero

In [779]:
# ct_vect = CountVectorizer()
# x_train = ct_vect.fit_transform(x_train).toarray()
# x_test = ct_vect.transform(x_test).toarray()

In [780]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [781]:
# pca = PCA()
# pca.fit(x_train_stand)
# cumsum = np.cumsum(pca.explained_variance_ratio_)*100
# d = [n for n in range(len(cumsum))]
# plt.figure(figsize=(10, 10))
# plt.plot(d,cumsum, color = 'red',label='cumulative explained variance')
# plt.title('Cumulative Explained Variance as a Function of the Number of Components')
# plt.ylabel('Cumulative Explained variance')
# plt.xlabel('Principal components')
# plt.axhline(y = 95, color='k', linestyle='--', label = '95% Explained Variance')
# plt.legend(loc='best')

In [782]:
# VARIANCE EXPLAINED 75%
# pca = PCA(n_components=0.90) 
# pca.fit(x_train_stand)
# x_train_pca = pca.transform(x_train_stand)
# x_test_pca = pca.transform(x_test_stand)

In [783]:
K = [int(i) for i in range(x_train.shape[0]//3)]
param_grid = {
    'n_neighbors' : K 
}
knn = KNeighborsClassifier()
grid_search = GridSearchCV(estimator=knn,scoring='accuracy',param_grid=param_grid,cv = 10,n_jobs = -1,verbose = 2)
grid_search.fit(x_train,y_train)
grid_search.best_estimator_
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

Fitting 10 folds for each of 530 candidates, totalling 5300 fits


KeyboardInterrupt: 

In [784]:
C = [0.01 , 0.05  , 0.08, 0.1, 0.3 , 0.6 , 0.9 , 1.2 , 1.7 , 2.5 , 2.9 , 3.7, 4.6 , 5.1 , 5.9 , 6.9 , 7.5 , 8.3 , 9.3 , 10]
kernel = ['linear', 'poly', 'rbf', 'sigmoid']
gamma = ['scale','auto']
degree = [int(x) for x in range(1,5)]
param_grid = {
    'kernel' : kernel,
    'gamma' : gamma,
    'degree' : degree,
    'C' : C
}
svc = SVC()
grid_search = GridSearchCV(estimator=svc,scoring='accuracy',param_grid=param_grid,cv = 5,n_jobs = -1,verbose = 2)
grid_search.fit(x_train_pca,y_train)

Fitting 5 folds for each of 640 candidates, totalling 3200 fits


In [ ]:
grid_search.best_params_

{'C': 2.5075, 'degree': 1, 'gamma': 'auto', 'kernel': 'rbf'}

In [ ]:
best_gird_search = grid_search.best_estimator_

In [ ]:
grid_search.best_estimator_

SVC(C=2.5075, degree=1, gamma='auto')

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = best_gird_search.predict(x_test_pca)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print(accuracy_score(y_train,best_gird_search.predict(x_train_pca)))
# Score = cross_val_score(best_gird_search,X_data,Y_data,cv = 5)
# Score

[[193   3]
 [201   1]]
Accuracy Score 0.48743718592964824
1.0


In [ ]:
from sklearn.metrics import accuracy_score
model = SVC(C = 25, degree= 4, gamma =  'auto', kernel = 'linear')
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
# Score = cross_val_score(model,X_data,Y_data,cv = 5)
# Score

[[102  94]
 [100 102]]
Accuracy Score 0.5125628140703518


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(12,input_shape = (x_train.shape[1],),activation = 'relu'))
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=200,batch_size=1000)



Epoch 1/200
2/2 [==============================] - 1s 7ms/step - loss: 0.6929 - accuracy: 0.5296
Epoch 2/200
2/2 [==============================] - 0s 10ms/step - loss: 0.6924 - accuracy: 0.5440
Epoch 3/200
2/2 [==============================] - 0s 11ms/step - loss: 0.6920 - accuracy: 0.5447
Epoch 4/200
2/2 [==============================] - 0s 8ms/step - loss: 0.6917 - accuracy: 0.5447
Epoch 5/200
2/2 [==============================] - 0s 7ms/step - loss: 0.6913 - accuracy: 0.5421
Epoch 6/200
2/2 [==============================] - 0s 12ms/step - loss: 0.6908 - accuracy: 0.5421
Epoch 7/200
2/2 [==============================] - 0s 10ms/step - loss: 0.6904 - accuracy: 0.5421
Epoch 8/200
2/2 [==============================] - 0s 8ms/step - loss: 0.6899 - accuracy: 0.5421
Epoch 9/200
2/2 [==============================] - 0s 11ms/step - loss: 0.6894 - accuracy: 0.5421
Epoch 10/200
2/2 [==============================] - 0s 10ms/step - loss: 0.6889 - accuracy: 0.5421
Epoch 11/200
2/2 [=====

In [ ]:
predictions = (model.predict(x_test) > 0.5).astype(int)
abs(predictions.T - y_test).sum()/y_test.shape[0]


13/13 [==============================] - 0s 2ms/step


0.5150753768844221

In [ ]:
randomclassifier=RandomForestClassifier(n_estimators=1000,criterion='entropy')
randomclassifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000)

In [ ]:
predictions = randomclassifier.predict(x_test)

In [ ]:
matrix=confusion_matrix(y_test,predictions)
print(matrix)
score=accuracy_score(y_test,predictions)
print(score)
report=classification_report(y_test,predictions)
print(report)

[[ 49 147]
 [ 39 163]]
0.5326633165829145
              precision    recall  f1-score   support

           0       0.56      0.25      0.35       196
           1       0.53      0.81      0.64       202

    accuracy                           0.53       398
   macro avg       0.54      0.53      0.49       398
weighted avg       0.54      0.53      0.49       398

